"""
Django settings for OneDjango project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kmyy1qml-r$t)e%%wlyo(a!!4vz1%^)m1rv!%=1r%-__jz%f$v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_vite',
    # 'app_index.apps.AppIndexConfig',
    'appone.apps.ApponeConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OneDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OneDjango.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'argoproject',
        'USER': 'postgres',
        'PASSWORD' : '123456',
        'HOST':'localhost',
        'PORT':'5432',
        'OPTIONS':{
            'options':
                '-c search_path=srelase'
        }
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

MEDIA_URL = 'media/'
STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / MEDIA_URL
STATIC_ROOT = BASE_DIR / STATIC_URL

VITE_SOURCE = 'src'
VITE_PUBLIC = 'public'
VITE_MODULE = 'vite4django'

STATICFILES_DIRS = [
    BASE_DIR / VITE_MODULE / VITE_PUBLIC,
    BASE_DIR / VITE_MODULE / VITE_SOURCE,
]

# DJANGO_VITE
PORT = 5173
VITE_HMR = '@vite/client'
PROTOCOL = 'http'
HOSTNAME = 'localhost'
MANIFEST = '.vite/manifest.json'

# DJANGO_VITE_DEV_MODE = DEBUG
# DJANGO_VITE_DEV_SERVER_PORT = PORT
# DJANGO_VITE_DEV_SERVER_PROTOCOL = PROTOCOL
# DJANGO_VITE_DEV_SERVER_HOST = HOSTNAME
# DJANGO_VITE_STATIC_URL_PREFIX = ''
# DJANGO_VITE_MANIFEST_PATH = STATIC_ROOT / MANIFEST
# DJANGO_VITE_WS_CLIENT_URL = VITE_HMR

DJANGO_VITE = {
    'default': {
        'dev_mode': DEBUG,
        'dev_server_port': PORT,
        'static_url_prefix': '',
        'ws_client_url': VITE_HMR,
        'dev_server_host': HOSTNAME,
        'dev_server_protocol': PROTOCOL,
        'manifest_path': STATIC_ROOT / MANIFEST,
    },
    'preview': {
        'dev_mode': False,
        'dev_server_port': 4173,
        'static_url_prefix': '',
        'ws_client_url': VITE_HMR,
        'dev_server_host': HOSTNAME,
        'dev_server_protocol': PROTOCOL,
        'manifest_path': STATIC_ROOT / MANIFEST,
    },
}

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sessions
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 3 * 60 * 60
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Cors
CORS_ALLOW_HEADERS = ['*']
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_CONTENT_TYPE_NOSNIFF = True

# Router
PREPEND_WWW = True
APPEND_SLASH = False
PAGE_SUFFIX = '.php'
LOGIN_URL = 'logon' + PAGE_SUFFIX
